import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amazona Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="bg-blue-400 p-2 ">Bismillah</h1>
      </div>
    </div>
  );
}
